language: go
sudo: false
go:
  - "1.9.x"
  - "1.10.x"
go_import_path: github.com/nmatsui/bearer-auth-api
install:
  - go get -u github.com/golang/lint/golint
script:
  - go vet ./...
  - diff <(golint ./...) <(printf "")
  - go test ./...
